#!/usr/bin/env bash
#
# Installs all cargo-managed dependencies required to build Warp.

# This script should be platform-agnostic (eg. no unix-only references like /dev/null).

# Install the Diesel CLI from its checksum-verified crates.io source archive.
#
# This is only needed for local development, so we skip it when running on GitHub
# (either for CI or building a release).
if [ "${GITHUB_ACTIONS}" != "true" ]; then
    cargo install diesel_cli@2.3.13 --locked --force
fi

# Install the internal channel config binary. This will fail gracefully for
# external contributors who don't have access to the private configuration.
"$PWD"/script/install_channel_config || echo "Skipping internal channel config installation (no repo access)."

if [ "$(uname -s)" = "Darwin" ]; then
    "$PWD"/script/macos/install_build_deps
fi
