#!/usr/bin/env bash
#
# Installs all cargo-managed dependencies required to build and test Warp.

# This script should be platform-agnostic (eg. no unix-only references like /dev/null).

"$PWD"/script/install_cargo_build_deps

# Keep this revision in sync with wgslfmt in CI. A commit is immutable; a tag can be moved.
cargo install --git https://github.com/wgsl-analyzer/wgsl-analyzer \
  --rev "7e34f03c702d3f9d37713236faf0576b1e9efae6" --locked wgslfmt

# Install nextest, which we use as our test execution harness.
cargo install cargo-nextest@0.9.144 --locked --force
